//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Integradora {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Integradora.IntegradoraSoap")]
    public interface IntegradoraSoap {
        
        // CODEGEN: Generating message contract since element name LeerRomResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeerRom", ReplyAction="*")]
        Test.Integradora.LeerRomResponse LeerRom(Test.Integradora.LeerRomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeerRom", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.Integradora.LeerRomResponse> LeerRomAsync(Test.Integradora.LeerRomRequest request);
        
        // CODEGEN: Generating message contract since element name rom from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EscribirRom", ReplyAction="*")]
        Test.Integradora.EscribirRomResponse EscribirRom(Test.Integradora.EscribirRomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EscribirRom", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.Integradora.EscribirRomResponse> EscribirRomAsync(Test.Integradora.EscribirRomRequest request);
        
        // CODEGEN: Generating message contract since element name texto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imprimir", ReplyAction="*")]
        Test.Integradora.ImprimirResponse Imprimir(Test.Integradora.ImprimirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imprimir", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.Integradora.ImprimirResponse> ImprimirAsync(Test.Integradora.ImprimirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeerRomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeerRom", Namespace="http://tempuri.org/", Order=0)]
        public Test.Integradora.LeerRomRequestBody Body;
        
        public LeerRomRequest() {
        }
        
        public LeerRomRequest(Test.Integradora.LeerRomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LeerRomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cara;
        
        public LeerRomRequestBody() {
        }
        
        public LeerRomRequestBody(int cara) {
            this.cara = cara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeerRomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeerRomResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.Integradora.LeerRomResponseBody Body;
        
        public LeerRomResponse() {
        }
        
        public LeerRomResponse(Test.Integradora.LeerRomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LeerRomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LeerRomResult;
        
        public LeerRomResponseBody() {
        }
        
        public LeerRomResponseBody(string LeerRomResult) {
            this.LeerRomResult = LeerRomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EscribirRomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EscribirRom", Namespace="http://tempuri.org/", Order=0)]
        public Test.Integradora.EscribirRomRequestBody Body;
        
        public EscribirRomRequest() {
        }
        
        public EscribirRomRequest(Test.Integradora.EscribirRomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EscribirRomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int cara;
        
        public EscribirRomRequestBody() {
        }
        
        public EscribirRomRequestBody(string rom, int cara) {
            this.rom = rom;
            this.cara = cara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EscribirRomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EscribirRomResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.Integradora.EscribirRomResponseBody Body;
        
        public EscribirRomResponse() {
        }
        
        public EscribirRomResponse(Test.Integradora.EscribirRomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EscribirRomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EscribirRomResult;
        
        public EscribirRomResponseBody() {
        }
        
        public EscribirRomResponseBody(bool EscribirRomResult) {
            this.EscribirRomResult = EscribirRomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImprimirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Imprimir", Namespace="http://tempuri.org/", Order=0)]
        public Test.Integradora.ImprimirRequestBody Body;
        
        public ImprimirRequest() {
        }
        
        public ImprimirRequest(Test.Integradora.ImprimirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImprimirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string texto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ip;
        
        public ImprimirRequestBody() {
        }
        
        public ImprimirRequestBody(string texto, string ip) {
            this.texto = texto;
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImprimirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImprimirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.Integradora.ImprimirResponseBody Body;
        
        public ImprimirResponse() {
        }
        
        public ImprimirResponse(Test.Integradora.ImprimirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImprimirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ImprimirResult;
        
        public ImprimirResponseBody() {
        }
        
        public ImprimirResponseBody(bool ImprimirResult) {
            this.ImprimirResult = ImprimirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntegradoraSoapChannel : Test.Integradora.IntegradoraSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegradoraSoapClient : System.ServiceModel.ClientBase<Test.Integradora.IntegradoraSoap>, Test.Integradora.IntegradoraSoap {
        
        public IntegradoraSoapClient() {
        }
        
        public IntegradoraSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegradoraSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegradoraSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegradoraSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.Integradora.LeerRomResponse Test.Integradora.IntegradoraSoap.LeerRom(Test.Integradora.LeerRomRequest request) {
            return base.Channel.LeerRom(request);
        }
        
        public string LeerRom(int cara) {
            Test.Integradora.LeerRomRequest inValue = new Test.Integradora.LeerRomRequest();
            inValue.Body = new Test.Integradora.LeerRomRequestBody();
            inValue.Body.cara = cara;
            Test.Integradora.LeerRomResponse retVal = ((Test.Integradora.IntegradoraSoap)(this)).LeerRom(inValue);
            return retVal.Body.LeerRomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.Integradora.LeerRomResponse> Test.Integradora.IntegradoraSoap.LeerRomAsync(Test.Integradora.LeerRomRequest request) {
            return base.Channel.LeerRomAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.Integradora.LeerRomResponse> LeerRomAsync(int cara) {
            Test.Integradora.LeerRomRequest inValue = new Test.Integradora.LeerRomRequest();
            inValue.Body = new Test.Integradora.LeerRomRequestBody();
            inValue.Body.cara = cara;
            return ((Test.Integradora.IntegradoraSoap)(this)).LeerRomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.Integradora.EscribirRomResponse Test.Integradora.IntegradoraSoap.EscribirRom(Test.Integradora.EscribirRomRequest request) {
            return base.Channel.EscribirRom(request);
        }
        
        public bool EscribirRom(string rom, int cara) {
            Test.Integradora.EscribirRomRequest inValue = new Test.Integradora.EscribirRomRequest();
            inValue.Body = new Test.Integradora.EscribirRomRequestBody();
            inValue.Body.rom = rom;
            inValue.Body.cara = cara;
            Test.Integradora.EscribirRomResponse retVal = ((Test.Integradora.IntegradoraSoap)(this)).EscribirRom(inValue);
            return retVal.Body.EscribirRomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.Integradora.EscribirRomResponse> Test.Integradora.IntegradoraSoap.EscribirRomAsync(Test.Integradora.EscribirRomRequest request) {
            return base.Channel.EscribirRomAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.Integradora.EscribirRomResponse> EscribirRomAsync(string rom, int cara) {
            Test.Integradora.EscribirRomRequest inValue = new Test.Integradora.EscribirRomRequest();
            inValue.Body = new Test.Integradora.EscribirRomRequestBody();
            inValue.Body.rom = rom;
            inValue.Body.cara = cara;
            return ((Test.Integradora.IntegradoraSoap)(this)).EscribirRomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.Integradora.ImprimirResponse Test.Integradora.IntegradoraSoap.Imprimir(Test.Integradora.ImprimirRequest request) {
            return base.Channel.Imprimir(request);
        }
        
        public bool Imprimir(string texto, string ip) {
            Test.Integradora.ImprimirRequest inValue = new Test.Integradora.ImprimirRequest();
            inValue.Body = new Test.Integradora.ImprimirRequestBody();
            inValue.Body.texto = texto;
            inValue.Body.ip = ip;
            Test.Integradora.ImprimirResponse retVal = ((Test.Integradora.IntegradoraSoap)(this)).Imprimir(inValue);
            return retVal.Body.ImprimirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.Integradora.ImprimirResponse> Test.Integradora.IntegradoraSoap.ImprimirAsync(Test.Integradora.ImprimirRequest request) {
            return base.Channel.ImprimirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.Integradora.ImprimirResponse> ImprimirAsync(string texto, string ip) {
            Test.Integradora.ImprimirRequest inValue = new Test.Integradora.ImprimirRequest();
            inValue.Body = new Test.Integradora.ImprimirRequestBody();
            inValue.Body.texto = texto;
            inValue.Body.ip = ip;
            return ((Test.Integradora.IntegradoraSoap)(this)).ImprimirAsync(inValue);
        }
    }
}
